// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eopdbgulvmunmykoyaha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvcGRiZ3Vsdm11bm15a295YWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDk2ODQsImV4cCI6MjA2MzgyNTY4NH0.WpOVQpr3vyWIWtfPk6prz-80KzncZLuWumIVQIsEsvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);